name: 删除7天前的日志

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码库
        uses: actions/checkout@v2

      - name: 安装依赖
        run: npm install -g github-actions-delete-logs

      - name: 删除7天前的日志
        run: |
          # 获取7天前的日期
          DATE=$(date -d "7 days ago" +%Y-%m-%d)

          # 删除日志
          github-actions-delete-logs --before $DATE
